spring.application.name=server

spring.datasource.url=jdbc:mysql://localhost:3306/hyperlocal_service
spring.datasource.username=root
spring.datasource.password=Ujwala@2027

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG

jwt.secret=7d5c9d6e6c5d4e2f8b8d9f7c3a1b5e6f7d8c9b0a1e2f3d4c5b6a7d8e9f0a1b2
jwt.expiration=86400000